#!/bin/bash

### This script is called after the user uninstalls the application.
rm -rf "${TRIM_APPDEST_VOL}/@appshare/hp-lite"
rm -rf "${TRIM_APPDEST_VOL}/@appconf/hp-lite"
rm -rf "${TRIM_APPDEST_VOL}/@appdata/hp-lite"
rm -rf "${TRIM_APPDEST_VOL}/@apphome/hp-lite"
rm -rf "${TRIM_APPDEST_VOL}/@appmeta/hp-lite"
rm -rf "${TRIM_APPDEST_VOL}/@apptemp/hp-lite"

exit 0